# LULC Classification Scheme {#sec-module-2}

# Module Overview {.unnumbered}

This module prompt the user to define the list of land cover or land use class which they're going to classified using the Luma platform. Luma supports user-defined classification schemes and default classification or templates for commonly used classification schemes.

# Input {.unnumbered}

| Name of input | Input Type | Details |
|------------------------|------------------------|------------------------|
| User's LULC list of classes | User's input | Entered with `.csv` file or manually defined on the UI |
| Other existing LULC list of classes | System's input | RESTORE+ LULC class |

# Output {.unnumbered}

LULC list of classes to be applied in the final classification result

# Process {.unnumbered}

::: callout-important
## Error Handling Notification

This module cannot be accessed if the system does not detect any saved satellite imagery from [Module 1](#sec-module-1).
:::

## Selection of Classification Scheme {#sec-selection-of-classification-schema}

This sub-step does not involve any operations within the Luma Geospatial Engine.

- If the user chooses to upload their own schema, the system proceeds to @sec-user-uploading-their-own-classification
- If the user chooses to define the classification manually on the UI, the system proceeds to @sec-user-entering-the-classification-manually
- If the user chooses a default classification scheme, the system proceeds to @sec-user-select-existing-lulc-template

### User Uploading Their Own Classification Scheme {#sec-user-uploading-their-own-classification}

1.  The system automatically detects column headers based on common naming conventions for ID, class name, and color code. If the expected headers are not found, the user must manually assign the correct column names.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.auto_detect_csv_columns()`: this function automatically detects the column headers. The set for the common naming conventions are currently hardcoded as the following:

    - For ID: "id", "classid", "kode", "code"
    - For class name: "classname", "class", "kelas", "name", "nama"
    - For color code: "color", "colorcode", "warna", "colour", "hex", "palette"
    :::

2.  The system validates the uploaded `.csv` to ensure IDs are numeric and unique, applies a set of distinct colors if no color code was provided by the user. The user can change the color code manually.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.process_csv_upload()`: to validate class data by checking ID integrity, assigning colors (`_generate_distinct_colors`), and returning a success status with a summary message.

    `classification_scheme.LULC_scheme_Manager._generate_distinct_colors()`: to generate a predefined set of distinct colors for LULC classes (up to 20). If the number of classes exceeds this limit, the method falls back to generating random colors via `_generate_random_colors()`.

    `classification_scheme.LULC_scheme_Manager._generate_random_colors()`: to generate random hex color code.

    `classification_scheme.LULC_scheme_Manager.finalize_csv_upload()`: to finalize the CSV file by applying any user-assigned colors, saving and sorting the class list, and clearing temporary data.
    :::

### User Entering the Classification Manually {#sec-user-entering-the-classification-manually}

1.  The system validates user-provided class input for numeric ID, non-empty class name, and uniqueness (if adding new classes).

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.validate_class_input()`: Validates class ID and name, checks for uniqueness, and returns a validity flag with an error message if invalid.

    `classification_scheme.LULC_scheme_Manager.add_class()`: Adds a new class or updates an existing class, validates inputs, assigns colors, sorts classes, and updates the next available ID.
    :::

2.  The system normalizes class name inputs through a sequential process: it first applies Unicode normalization using the NFKD form, converts all characters to lowercase, replaces common separators (`_`, `-`) with spaces, removes non-alphanumeric characters, collapses multiple consecutive spaces, and applies light lexical normalization to reduce superficial grammatical differences, such as singular versus plural forms (e.g. “forest” and “forests”). Missing values (`None` or `NA`) are returned as None. Optionally, words within the class name can be sorted alphabetically to enable order-independent matching (e.g. “Forest Mixed” = “Mixed Forest”)

3.  Temporary edit mode flags are managed to differentiate between adding and updating classes.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.edit_class()`

    `classification_scheme.LULC_scheme_Manager.delete_class()`

    `classification_scheme.LULC_scheme_Manager.cancel_edit()`
    :::

### User Selecting a Default Classification Scheme {#sec-user-select-existing-lulc-template}

1.  The system loads the chosen classification scheme classes.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.load_default_scheme()`: to load an existing classification scheme from a dataset.

    `classification_scheme.LULC_scheme_Manager.get_default_schemes()`: stores the RESTORE+ LULC class in a dictionary.
    :::

2.  If the user selects a subset of the default classes, the system stores the selection into a variable that will be used for the reclassification process in [Module 6](#sec-module-6).

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.store_classes_of_interest()`: to store the user's class of interest as a variable that will be used for the reclassification process in Module 6.
    :::

## Saving and Downloading the LULC Classification Table {#sec-saving-the-lulc-classification-table}

### Saving and Downloading the LULC Classification Table

1.  The system generates a `.csv` file containing the final LULC classification scheme table.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.get_csv_data()` : to generate a `.csv` file containing the final classification table that has been standardized by `get_dataframe`.

    `classification_scheme.LULC_scheme_Manager.get_dataframe()` : to standardize the column names of the LULC classification table to "ID", "Land Cover Class", "Color Palette"
    :::

2.  The system checks whether the user has defined at least one class.

    ::: callout-tip
    ## Related Functions

    `classification_scheme.LULC_scheme_Manager.has_classes()`: to check if any classes are defined.

    `classification_scheme.LULC_scheme_Manager.get_class_count()`: get the information of the number of the defined classes.
    :::

3.  The system saved the LULC class classification scheme as an object to be loaded in the next modules.