# LULC Map Generation {#sec-module-6}

# Module Overview {.unnumbered}

This module performs supervised Random Forest classification to generate a land cover map. It includes input review, hyperparameter definition, feature extraction, model training, hard/soft classification, feature importance, and accuracy evaluation using test data.

# Input {.unnumbered}

| Name of input | Input type | Details |
|------------------------|------------------------|------------------------|
| Sample data split proportion | User's input | Optional, if not set then use default value |
| Random Forest (RF) parameters | User's input | Optional, if not set then use default value |
| Satellite imagery within the AOI | Input from other modules | Module 1 |
| LULC classes | Input from other modules | Module 2 |
| Sample data | Input from other modules | Module 3 |

# Output {.unnumbered}

1.  Trained LULC classification model.
2.  Model accuracy report if validatndefinedion data available (including overall accuracy, precision, recall, F1-score, Kappa, model error matrix). This output is only available if the user has a validation data from the [splitted the sample data](@sec-sec-data-split)
3.  Classified LULC raster map.

# Process {.unnumbered}

::: callout-important
## Error Handling Notification

This module cannot be accessed if the system is missing the required inputs from the Input from Other Modules
:::

## Checking Prerequisites from Previous Modules {#sec-checking-prerequisites}

This is a part of **System Response 6.1: Reviewing input specifications for model training**

### Checking Prerequisites from Previous Modules

**Luma User Journey**

1.  The user is displayed a verification of the required inputs stored in the system.

**Luma Geospatial Engine**

1.  The system validates availability of the required inputs.

## Extracting spectral feature from sample data {#sample-data-feature-extraction}

### Splitting the sample data {#sec-data-split}

**Luma User Journey**

1.  The user defines the proportion to split the sample data into training and validation dataset.

2.  If the user does not split the sample data, the system shows a warning that all the sample data will be used as training data.

3.  The user is required to set feature extraction parameter, including class label column and the pixel size.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation that feature extraction has been completed, and the summary of the number of training data and validation data split.
    :::

**Luma Geospatial Engine**

1.  The system conducts feature extraction for both training and validation data accordingly to the proportion set by the user.

2.  The system uses stratified random split method to conduct the data splitting. This method randomly selects samples within each class to proportionally create training and testing sets while preserving class distribution.

    ::: callout-tip
    ## Related Functions

    `classification.FeatureExtraction.stratified_split()` : performs stratified random split of sample data based on LULC class labels.
    :::

## Creating classification model {#sec-create-classification-model}

### Creating classification model

**Luma User Journey**

This is a part of **User Journey 6.2: Determining classification's specification**

1.  The user is given the option to use default value of the RF parameters. The default value are as the following:

    -   Number of trees: 50, 100, or 150 are given as options
    -   Variables per split: square root of total spectral band features used
    -   Minimum leaf population: 1

2.  The user is given the option to manually configure the classification parameter:

    -   Number of trees
    -   Variables per split: square root of total spectral band features used, or can adjust manually
    -   Minimum leaf population

3.  The user is prompted to verify the inputs and run the process to create the classification model.

    ::: callout-important
    ## Error Handling Notification

    The process to create a classification model is disabled if the user has not extracted the spectral feature
    :::

    ::: callout-note
    ## Success Notification

    The system shows a confirmation that a classification model has been created.
    :::

**Luma Geospatial Engine**

This is a part of **System Response 6.2: Classification process**

1.  The system create the classification model using hard classification method.

    ::: callout-tip
    ## Related Functions

    `classification.Generate_LULC.hard_classification()` : trains a RF classifier (`smileRandomForest`) using extracted training data and applies it to the input imagery to produce a hard (pixel-level) multiclass.
    :::

### Reviewing classification model's quality {#sec-review-model-result}

**Luma User Journey**

This is a part of **User Journey 6.3: Review classification result**

1.  The user is shown a feature-importance graph displaying each variable used to train the classification model. In this development phase, only spectral bands are used as classification variables.

2.  The user is prompted to begin the process of calculating the model’s accuracy assessment.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation of the completion of model accuracy assessment.
    :::

3.  The user is shown the results of the model’s accuracy assessment, presented in the following structure:

    -   Overall model accuracy (overall accuracy percentage, kappa coefficient, average F1-score, and G-Mean score)

    -   Class-level accuracy (producer’s accuracy, user’s accuracy, F1-score, and G-Mean score), also visualized in a confusion matrix with an accompanying highlight summary of the LULC classes with the lowest accuracy.

**Luma Geospatial Engine**

This is a part of **System Response 6.3: Testing model's accuracy**

1.  The system extracts feature importance from the trained Random Forest model and presents a ranked table of bands (or a fallback equal-weight estimate if true importance is unavailable).

    ::: callout-tip
    ## Related Functions

    `classification.Generate_LULC.get_feature_importance()` : extracts and returns model feature importance as a dataframe; if the model explanation is not available, falls back to an equal-weight estimate.
    :::

2.  The system calculates model evaluation metrics on the validation dataset.

    ::: callout-tip
    ## Related Functions

    `classification.Generate_LULC.evaluate_model()` :classifies the validation data with the trained classifier, builds the confusion matrix, and returns a dictionary of accuracy metrics
    :::

3.  Confusion matrix and model accuracy summary are then rendered in the user-interface.

### Visualizing LULC classification map result {#sec-view-classification-map}

**Luma User Journey**

1.  This step is optional for the user.

2.  The user can visualizes the LULC classification result on a canvas map along with the training data layer.

3.  The user is given the option to adjust the class color visualization, or to reset it accordingly with the saved determined color saved in [Module 2](@sec-module-2).

**Luma Geospatial Engine**

This sub-step does not involve any operations from Luma Geospatial Engine.

### Downloading the LULC classification map result

**Luma User Journey**

1.  This step is optional for the user.

2.  The user can download the classified LULC map through two options:

    a.  Direct download: Downloads the image locally in the user's device. This option is only available if the classification map result is less than 32 MB.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation if the URL for direct download of classified LULC map is successfully made.
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if the system fails to create the URL for direct download and suggests the user to use Google Cloud Storage instead.
    :::

    b.  Export to Google Cloud Storage: Downloads the image to Google Cloud Storage.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation if the classified LULC map is successfully saved to Google Cloud Storage.
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if the system fails to export the classified LULC map to Google Cloud Storage.
    :::

**Luma Geospatial Engine**

1.  This sub-step does not involve any operations from Luma Geospatial Engine. Direct download settings are defined from Streamlit, using the same workflow as defined in @sec-visualization-and-saving-data.

2.  For details on exporting to Google Cloud Storage, refer to Earth Engine Initialization and Authentication page.