project:
  type: book

book:
  title: "Luma Development Reference"
  # author: 
  # date: "18/09/2025"
  chapters:
    - index.qmd
    - writing_guidelines.qmd
    - testing_guidelines.qmd
    - part: "General Development Settings"
      chapters: 
        - python_setup.qmd
        - ee_init.qmd
        - helpers.qmd
    # - intro.qmd
    - part: "Luma Modules"
      chapters:
      - 01_data_acquisition.qmd
      - 02_classification_scheme.qmd
      - 03_sample_data.qmd
      - 04_sample_data_quality.qmd
      - 05_predictor.qmd
      - 06_classification.qmd
      - 07_accuracy.qmd
      - placeholders/module08_placeholder.qmd
    # - summary.qmd
    # - references.qmd
  sidebar:
    logo: images/epistem_logo_color.png
    search: true
    tools:
      - icon: globe
        href: https://epistem.io/
      - icon: file-pdf
        href: files/visio_bootcamp.pdf
      - icon: github
        href: https://github.com/epistem-io/luma-stack
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    number-depth: 5
    

  pdf:
    documentclass: scrreprt

editor: visual

