project:
  type: book

book:
  title: "Luma Development Reference"
  # author: 
  # date: "18/09/2025"
  chapters:
    - index.qmd
    - writing_guidelines.qmd
    - testing_guidelines.qmd
    - part: "General Development Settings"
      chapters: 
        - python_setup.qmd
        - ee_init.qmd
        - helpers.qmd
    # - intro.qmd
    - part: "Luma Modules"
      chapters:
      - module01.qmd
      - module02.qmd
      - module03.qmd
      - module04.qmd
      - placeholders/module05_placeholder.qmd
      - module06.qmd
      - module07.qmd
      - placeholders/module08_placeholder.qmd
    # - summary.qmd
    # - references.qmd
  sidebar:
    logo: images/epistem_logo_color.png
    search: true
    tools:
      - icon: globe
        href: https://epistem.io/
      - icon: file-pdf
        href: files/visio_bootcamp.pdf
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    number-depth: 5
    

  pdf:
    documentclass: scrreprt

editor: visual

