# Map Generation {#sec-map-generation .unnumbered}

# Overview {.unnumbered}

In this workflow, the user produces a Land Use and Land Cover (LULC) map. Each step is presented as a panel on the left of the map canvas and progresses via the indicator at the top of the panel. The user cannot skip steps; each step unlocks the next only after the Geospatial Engine (GE) confirms the required output has been produced and saved.

# Step 1: Basic Information {#sec-map-generation-basic-information}

**Overview**

Provides the inputs needed before any geospatial computation: where to map, when, and from which satellite source.

## Step 1.1: Geographic Area

**Overview**

This is the first required input in the Map Generation workflow where the user specify the geographic area they want to map.

### Step 1.1.1: Upload Area

**Overview**

The user uploads a polygon file to define the geographic boundary of the area they want to map.

**Process**

1.  The user can upload their own AOI file in `.zip` format that includes all required shapefile components (`.shp`, `.shx`, `.dbf`, `.prj`).

2.  The system checks on all required shapefile components that needs to be put in the `.zip` file. The system also supports uploads of `.kml` or `.kmz` files.

    ::: callout-note
    ## Success Notification

    If shapefile components are all good, allowed to continue to Process 3
    :::

    ::: callout-important
    ## Error Handling Notification

    If shapefile components do not match, error warning displayed: 'No `.shp` file found in the `.zip` file.’
    :::

3.  The system retrieves AOI file information.

    ::: callout-note
    ## Success Notification

    If file information are all good, allowed to continue to Process 4
    :::

    ::: callout-important
    ## Error Handling Notification

    If file information cannot be found, error warning displayed: 'AOI not found’
    :::

4.  The system retrieves AOI file area size information.

    ::: callout-note
    ## Success Notification

    If area size information is within maximum area allowed, continue to Process 5
    :::

    ::: callout-important
    ## Error Handling Notification

    If area size information is too large, error warning displayed: 'Draw area exceeds maximum limit’
    :::

5.  The system validates the geometry of the AOI for both `.shp` and `.kml` using [the `shapefile_validator` functions](@sec-validation-of-shapefile-geometries).

    ::: callout-note
    ## Success Notification

    If validation is all good, allowed to continue to Process 6
    :::

    ::: callout-important
    ## Error Handling Notification

    If validation is not good, Interface will have an error warning displayed: 'Geometry validation failed.'
    :::

6.  The system returns the validated and processed shapefile.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation when the AOI is loaded successfully by showing a purple box with "Approximate size of your mapping area: X [number] Ha" displayed
    :::

7.  If the user clicks on "Reselect Area", the uploaded file is deleted, and the user will be redirected to @sec-map-generation-basic-information.

### Step 1.1.2: Draw Area

**Overview**

The user draws their area of interest directly on the map by creating borders of area they want to map. Each click adds a new corner to the polygon, with a double-click to finish drawing and close the polygon. This is useful when the user does not have a prepared polygon file or wants to quickly define a simple area.

**Process**

1.  The user creates a polygon by clicking on the map and selects a spatial resolution from the available options.

2.  The system retrieves the AOI area size information.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation when the AOI is loaded successfully by showing a purple box with "Approximate size of your mapping area: X [number] Ha" displayed
    :::

    ::: callout-important
    ## Error Handling Notification

    If area size information is too large, error warning displayed: 'Draw area exceeds maximum limit’
    :::

3.  If the user clicks on "Reselect Area", the polygon is deleted, and the user will be redirected to @sec-map-generation-basic-information.

### Step 1.1.3: Administrative Boundaries

**Overview**

The user selects the area they want to map based on a drop down list of Indonesian regency administrative boundaries. The system provides a preview of the selected boundary.

**Process**

1.  The user selects an administrative boundary from the dropdown and a spatial resolution from the available options.

2.  The system retrieves the AOI information from the selected administrative boundary selections. The system runs the related functions in @sec-aoi-from-administrative-boundary and provides a preview of the selected boundary.

## Step 1.2: Time Period {#sec-map-generation-time-period}

**Overview**

The user defines the time period for the land use and land cover map. User chooses the range of period of satellite imagery in a single year format or a custom date range format.

**Process**

1.  The user chooses a time interval selection ("By year") and a year (1972–current year).

2.  The system retrieves the selected year and the options for the Satellite Imagery (@sec-map-generation-satellite-imagery) are limited to the available sensor images depending on the selected year.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation by showing a purple box with a summary of: time interval, period, satellite imagery date range selected
    :::

    ::: callout-important
    ## Error Handling Notification

    If time interval nor year is not selected, the options on Satellite Imagery (@sec-map-generation-satellite-imagery) are not available
    :::

3.  The user chooses a time interval selection (”Custom date range”) along with the start and end dates.

4.  The system provides a preview of calendar for user to choose the start and end dates.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation by showing a purple box with a summary of: time interval, period, satellite imagery date range selected
    :::

    ::: callout-important
    ## Error Handling Notification

    If time interval nor date range is not selected, the options on Satellite Imagery (@sec-map-generation-satellite-imagery) are not available
    :::

## Step 1.3: Satellite Imagery {#sec-map-generation-satellite-imagery}

**Overview**

The user chooses a satellite imagery source and sets the maximum cloud coverage. The system retrieves all available scenes, removes cloudy pixels, and combines the rest into a single cloud-free composite image. This composite is the base image for all classification steps. Three visualisation modes are generated: True Colour (RGB), False Colour Infrared, and Land/Water.

**Process**

1.  The system checks the selected year in @sec-map-generation-time-period and shows the available sensors based on the selected year.

2.  The user sets a preferred cloud cover threshold, if none chosen, the default value of 30% is used.

3.  The system performs pre-processing functions in @sec-input-spatial-image-parameters.

    ::: callout-note
    ## Success Notification

    When all information is collected, allowed to continue to Process 4
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if no satellite images were found based on the user’s parameter. The user is prompted to change the cloud cover threshold or change the time period.
    :::

4.  The system returns the collected satellite image information.

    ::: callout-note
    ## Success Notification

    The user’s input summary is displayed in a purple box, showing:

    - Mapping area: approximate size of your mapping area
    - Time period selected: time interval, selected period, satellite input date range
    - Satellite imagery: satellite imagery source, maximum cloudy area

    Two buttons appear:

    - Change Input; if selected, continue to Process 5
    - View Satellite Imagery; if selected, continue to Process 8
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if no satellite images were found based on the user’s parameter. The user is prompted to change the cloud cover threshold or change the time period.
    :::

5.  If the user clicks on the "Change Input" button, "Edit" (pencil) buttons appear next to each of the input summary’s heading. Once clicked, a pop up window appeared for user to choose:

- "Change Input", continue to Process 6, or
- "Discard Changes", continue to Process 7.

6.  If the user clicks on the "Change Input" button in the pop up window, all inputs are being reset, back to the beginning of @sec-map-generation-basic-information.

7.  If the user clicks on the "Discard Changes" button in the pop up window, the panel still displays the user’s input summary. "Cancel Change" button appear, while "View Satellite Imagery" is disabled. Once the "Cancel Change" button is clicked, back to Process 4.

8.  If the user clicks on the "View Satellite Imagery" button, the system returns the collected satellite image information.

    ::: callout-note
    ## Success Notification

    - A table of Generated Composite of Imagery Obtained appeared under the User’s Input Summary along with Cloud Coverage Statistic.
    - Composite of satellite imagery appears on the base map, with default setting of true colour (RGB).
    - Layers option appears on the bottom right corner of the screen, includes:
    - Mapping area; with polygon toggle
    - Composite of satellite imagery; with true colour (RGB), false colour infrared (NIR/Red/Green), land/water (NIR/SWIR1/RED) toggle options
    - LULC class; still disabled in this step
    - User can then download the composite, leading to Process 9.
    - Next button appears, which leads to @sec-map-generation-lulc-classification.
    :::

9.  If the user downloads composite, a `.zip` file containing satellite image composite is downloaded to user’s local device.

# Step 2: Land Use and Land Cover Classification {#sec-map-generation-lulc-classification}

**Overview**

The user defines the land use and land cover classes that will be mapped. There are two main options: using the built-in Luma default classification scheme or uploading a custom classification scheme. The selected classes determine which training data will be used in the next step. The Epistem-AI feature is also available here.