# Module 0 Name of the Module {#sec-module-0}

# Module Overview {.unnumbered}

A quick summary of the module is put here

# Input {.unnumbered}

**User's Input**

-   A list of inputs for the module's system from the user

**Input from External Sources**

-   A list of inputs for the module's system not from the user

**Input from Other Modules**

-   A list of inputs that are generated from other modules, referred to by the section's ID

# Output {.unnumbered}

-   A list of output generated from the module

# Process {.unnumbered}

Embed the Visio chart here for the module

## Step X

### Sub-Step {#sec-sub-step-example}

#### LUMA User Journey

This would be the "User Journey" part in Visio (white box)

::: callout-important
## Error Handling Notification

This part shows the error notifications that will be shown to the users for each of the guardrails set on the Geospatial Engine
:::

#### LUMA Geospatial Engine

This would be the "System Response" part in Visio (pink box)

::: callout-tip
## Related function

Write the file in which the function was called from (e.g, `from epistemx.helpers import get_aoi_from_gaul` means the function `get_aoi_from_gaul` was called from `helpers.py`)
:::

::: callout-warning
## Feature Status

Write the feature status on the related functions from the agreed discussion in Notion.
:::
