# Acquisition of Near-Cloud-Free Satellite Imagery {#sec-module-1}

# Module Overview {.unnumbered}

The output of this module is near–cloud-free satellite imagery that corresponds to the user-defined area of interest, which is essential for generating accurate and reliable land use and land cover (LULC) datasets. This module emphasizes the generation of pre-processed and corrected satellite imagery, incorporating procedures such as cloud masking and shadow removal.

# Input {.unnumbered}

| Name of Input | Input Type | Details |
|----------------------------------|-------------------|-------------------|
| Area of Interest | User's input |  |
| Target map date | User's input | YYYY or DD-MM-YYYY |
| Desired spatial resolution | User's input | in meters |
| Maximum allowable cloud cover | User's input | in percentage |
| Raw satellite imagery | System's input |  |
| Area of Interest from administrative boundaries | System's input |  |

# Output {.unnumbered}

1.  Selected AOI.
2.  Near-cloud-free satellite imagery.

# Process {.unnumbered}

## Selection of AOI {#sec-selection-of-aoi}

### AOI from Shapefile {#sec-aoi-from-shapefile}

**LUMA User Journey**

This is a part of **User Journey 1.1: Prerequisite Check**

1.  The user can upload their own AOI file in `.zip` format that includes all required shapefile components (`.shp`, `.shx`, `.dbf`, `.prj`). The system emphasizes on all required shapefile components that needs to be put in the `.zip` file.

2.  The system validates whether the `.zip` file includes all the required shapefile components.

::: callout-important
## Error Handling Notification

The system provides an error notification if the `.shp` file is not found inside the `.zip` file.
:::

3.  The AOI file is saved in a temporary directory, allowing users to go back-and-forth in between modules without having to re-uploading the AOI file.

**LUMA Geospatial Engine**

This sub-step does not involve any operations within the LUMA Geospatial Engine.

## Correction of Shapefile Geometries {#sec-validation-of-shapefile-geometries}

### Correction of Shapefile Geometries

**LUMA User Journey**

This is a part of **User Journey 1.1: Prerequisite Check**

1.  After the user uploads the AOI, they receive a continuous feedback on each the validation process.

::: callout-note
## Success Notification

The system shows a confirmation when the AOI is loaded successfully.
:::

::: callout-important
## Error Handling Notification

The system provides an error notification if shapefile validation fails.
:::

2.  Once the system succeeded to validate the shapefile input, the system displays the AOI on a map canvas.

**LUMA Geospatial Engine**

This is a part of **System Response 1.1: Area of Interest Definition**

1.  The system performs a multi-step geometry sanitization process before converting any shapefile or GeoDataFrame into Earth Engine objects. **These input validation processes for shapefiles are designed mainly for Streamlit compatibility**. Each correction is handled by exactly one dedicated function:

    -   The Coordinate Reference System (CRS) is automatically corrected and reprojected to WGS 1984 (EPSG:4326).

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.fix_crs():` to resolve coordinate reference system issues.
    :::

    -   Invalid, empty, or topologically broken geometries are detected and repaired.

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.clean_geometries():` to repair invalid geometries.
    :::

    -   An initial structural validation and basic geometry fixing.

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.validate_and_fix_geometry():`to validate and fix geometries issues.
    :::

    -   Polygon-specific validation, including removal of invalid coordinates and simplification of overly complex shapes.

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.validate_polygons():` to checks point geometries, remove invalid coordinates, and simplify polygon geometries.
    :::

    -   Every individual coordinate is checked to ensure it falls within valid global latitude/longitude ranges.

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.is_valid_coordinate():` to checks point geometries, remove invalid coordinates, and simplify polygon geometries.
    :::

    -   The number of vertices in each geometry is counted and logged (for diagnostic and simplification decisions).

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.count_vertices():` to checks point geometries, remove invalid coordinates, and simplify polygon geometries.
    :::

    -   Finally, a comprehensive pre-upload validation is executed to guarantee that every geometry is valid, non-empty, correctly typed, and fully compatible with Earth Engine.

    ::: callout-tip
    ## Related Functions

    `input_utils.shapefile_validator.final_validation():` to checks point geometries, remove invalid coordinates, and simplify polygon geometries.
    :::

2.  After the system succeeded to validate the shapefile, the system converted the GeoDataFrame file format into Earth Engine geometry format.

::: callout-tip
## Related Functions

`input_utils.EE_converter.convert_aoi_gdf():` to conduct the conversion of `.gdf` input file into `ee.geometry` . Three different conversion approaches was defined in this function:

-   Primary method: using `geemap.gdf_to_ee()`

-   If primary method fails, proceed to secondary method: manual GeoJSON conversion by union multiple geometries first (`gpd.GeoDataFrame([{'geometry': union_geom}], crs=gdf.crs)`) and convert it to GeoJSON (`gdf.to_json()`). **Only polygon and multipolygon geometry type is supported in this method**.

-   If both primary and secondary method fails, proceed to the last option: bounding box conversion to estimate the rectangular approximation of the AOI (`ee.Geometry.Rectangle([bounds[0], bounds[1], bounds[2], bounds[3]])`).
:::

## Selection and Preparation of Satellite Imagery

### Satellite Data Acquisition and Filtering {#sec-input-spatial-image-parameters}

**LUMA User Journey**

This is a part of **User Journey 1.2: Determining Satellite Imageries Parameters**

1.  The user is prompted to fill in these parameters for the satellite imagery:

    -   Target map date: Choose the range of period of satellite imagery in a single year format (YYYY) or full-date format (YYYY-MM-DD). If YYYY is used as the input format, the year option starts from 1972 until present year. The year 2020 is shown as the default option.

    -   Spatial resolution: Specify the desired spatial resolution. During Phase 1, only Landsat data will be utilized; therefore, the spatial resolution will be set on default to 30 meters.

    -   Sensor type: a list of sensors available based on the selected target map date input parameter. Landsat 8 OLI is shown to be the default option.

        ::: callout-important
        ## Error Handling Notification

        Since only Landsat data is utilized, the system provides an error notification if no Landsat sensor is available in the selected time range.
        :::

        ::: callout-warning
        ## Feature Notes

        A warning should be provided about the limited availability of Landsat 1-3 data if the user uses temporal scope input between 1972-1984.
        :::

    -   Maximum cloud cover: Set a preferred cloud cover threshold, or use the default value of 30%.

2.  The system provides information on satellite image availability shows the number of total satellite images found based on the user parameter input. The information includes total images found, date range of images, WRS tiles, path row tiles, scene IDs, image acquisition dates, average scene cloud cover, date range, and cloud cover range.

    ::: callout-note
    ## Success Notification

    The system shows the total number of satellite images found.
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if no satellite images were found based on the user's parameter. The user is prompted to change the cloud cover threshold or change the target map date.
    :::

**LUMA Geospatial Engine**

This is a part of **System Response 1.2: Search and Filter Imagery**

1.  The system specifies Landsat data collections for optical processing.

    ::: callout-tip
    ## Related Functions

    `data_acquisition.Reflectance_Data.OPTICAL_DATASETS` defines the properties of Landsat Surface Reflectance (SR) collections (Collection 2, Level-2) to be fetched for optical data processing.
    :::

    The system currently supports Landsat 1-3 RAW collection and and Landsat 4-9 surface reflectance (SR) collection. Additionally, Landsat 4 - 9 Top-of-Atmosphere (TOA) is used for retrieving thermal band as additional input band for the classification. This consideration stems from Landsat SR collection thermal band quality which often resulted in no data and prone to over-correction in high contrast land cover feature. Landsat mission availability is as follows:

    -   Landsat 1 Multispectral Scanner/MSS (1972 - 1978)
    -   Landsat 2 Multispectral Scanner/MSS (1978 - 1982)
    -   Landsat 3 Multispectral Scanner/MSS (1978 - 1983)
    -   Landsat 4 Thematic Mapper/TM (1982 - 1993)
    -   Landsat 5 Thematic Mapper/TM (1984 - 2012)
    -   Landsat 7 Enhanced Thematic Mapper Plus/ETM+ (1999 - 2021)
    -   Landsat 8 Operational Land Imager/OLI (2013 - present)
    -   Landsat 9 Operational Land Imager-2/OLI-2 (2021 - present)

2.  The system retrieves images that match user’s selected criteria, including spatial resolution, year, and cloud cover based on the following input parameters: AOI, target map date, and cloud cover threshold.

    ::: callout-tip
    ## Related Functions

    `data_acquisition.Reflactance_Data.get_optical_data():` to retrieve and the Landsat image collection based on the input parameters. This function uses the `mask_landsat_sr`, `apply_scale_factors`, and `rename_landsat_bands` to return a masked, scaled, and renamed image collection.
    :::

    -   The system performs cloud masking with QA_PIXEL band that encodes pixel conditions using specific bit flags. Bitwise AND operation are applied to isolate these conditions, focusing on clouds (bit 4, value 16) and cloud shadows (bit 3, value 8). Pixels matching these flags are excluded to produce a cleaner, near cloud-free image.

        ::: callout-tip
        ## Related Functions

        `data_acquisition.Reflactance_Data.mask_landsat_sr()`: Mask clouds, shadows and cirrus for Landsat Collection 2 SR using QA_PIXEL band.
        :::

        ::: callout-caution
        ## Feature Notes

        If Landsat 5-9 is selected, then `data_acquisition.Reflactance_Data.mask_landsat_sr()` should also implement **cirrus** masking using QA_PIXEL band. For now, the masking is only performed for cloud and cloud shadow.
        :::

    -   The system applies scaling to the optical reflectance bands to convert the raw digital numbers (DNs) into physically meaningful surface reflectance values. A scale factor 0.0000275 and offset -0.2 are applied, as defined in the Landsat Collection 2 Surface Reflectance metadata. This conversion standardize the reflectance values to a range of approximately 0 to 1, enabling accurate comparison and analysis across different scenes and sensors.

        ::: callout-tip
        ## Related Functions

        `data_acquisition.Reflactance_Data.apply_scale_factors()`: to apply Landsat collection 2 scalling factors using the following formula: Digital Number (DN) \* scale_factor + offset. The scale factor will only be applied to optical bands.
        :::

    -   The system renames the bands accordingly with the sensor type input.

        ::: callout-tip
        ## Related Functions

        `data_acquisition.Reflactance_Data.rename_landsat_bands()`: to standardize Landsat Surface Reflectance (SR) band names based on sensor type. From 'SR_B*' or 'B*' to 'NIR', 'GREEN', etc.
        :::

3.  The system then use the same parameter as multispectral data and use it to search collection 2 TOA data, except for Landsat 1-3 MSS. The TOA data thermal band (namely, band 10) is then stacked with multispectral band from SR data. Since band 11, contain larger calibration uncertainty, only band 10 is used. No additional pre-processing is conducted for thermal band since digital number value alone is considered satisfactory for discriminating land cover features.

    ::: callout-tip
    ## Related Functions

    `data_acquisition.Reflactance_Data.get_thermal_bands():` to retrieve and the Landsat image collection based on the input parameters.
    :::

4.  The system evaluates whether the retrieved imagery meets the required spatial resolution, input year, and cloud cover thresholds. If suitable images are found, the system generates a composite by calculating the median value across the selected imagery, as implemented using the `median()` function from Earth Engine. The system also then clips and mosaics the satellite imagery.

    ::: callout-caution
    ## Feature Notes

    Creating composite, clip, and mosaic of the image collection is currently conducted on Streamlit.
    :::

## Visualization and Saving of Processed Satellite Imagery {#sec-visualization-and-saving-data}

### Visualization and Saving Processed Satellite Imagery

**LUMA User Journey**

This is a part of **User Journey 1.3: Download Satellite Imagery**

1.  The system visualize the satellite imagery on a canvas map in bands NIR (near-Infrared), RED, and GREEN. The map is centralized on the AOI.

2.  The user can download the satellite imagery through two options:

    a.  Direct download: Downloads the image locally in the user's device. This option is only available if the satellite image is less than 32 MB. Direct download settings are defined from Streamlit.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation if the URL for direct download of satellite imagery is successfully made.
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if the system fails to create the URL for direct download and suggests the user to use Google Cloud Storage instead or use smaller AOI area.
    :::

    b.  Export to Google Cloud Storage: Downloads the image to Google Cloud Storage.

    ::: callout-note
    ## Success Notification

    The system shows a confirmation if the satellite image is successfully saved to Google Cloud Storage.
    :::

    ::: callout-important
    ## Error Handling Notification

    The system provides an error notification if the system fails to export the image to Google Cloud Storage.
    :::

3.  The user is given the option to continue to [Module 2](@sec-module-2)

    ::: callout-important
    ## Error Handling Notification

    The system disables the option to continue to the next module if the system does not detect a satellite imagery saved inside the system.
    :::

**LUMA Geospatial Engine**

This is a part of **System Response 1.3: Download Satellite Imagery and Continue to Next Module**

1.  The system collects the statistics of the satellite images found.

    ::: callout-tip
    ## Related Functions

    `data_acquisition.Reflactance_Stats.get_collection_statistics():` to get comprehensive statistics about the gathered image collection.
    :::

2.  For details on exporting to Google Cloud Storage, refer to Earth Engine Initialization and Authentication page.

3.  The system saved the satellite imagery as an object to be loaded in the next modules.
